export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG';
export const CHANGE_LYRIC = 'player/CHANGE_LYRIC';
export const CHANGE_MAYBEPLAYLIST = 'player/CHANGE_MAYBEPLAYLIST';
export const CHANGE_SEQUENCELAYLIST = 'player/CHANGE_SEQUENCELAYLIST';
export const CHANGE_MUSICPLAYLIST = 'player/CHANGE_MUSICPLAYLIST';
export const CHANGE_PLAYMODE = 'player/CHANGE_PLAYMODE';
