export const CHANGE_CATEGORIES = 'explore/CHANGE_CATEGORIES';

export const CHANGE_SEARCH_CATEGORIE = 'explore/CHANGE_SEARCH_CATEGORIE';

export const CHANGE_EXPLOER_LIST = 'explore/CHANGE_EXPLOER_LIST';

export const CHANGE_HASMORE = 'explore/CHANGE_HASMORE';

export const CHANGE_LOADING = 'explore/CHANGE_LOADING';
